### ISSUE TITLE
Yank breaking versions with "*" deps

### ISSUE THREAD

**Issue by kornelski** [conduit-rust/conduit#20]
An old version of `conduit` has dependencies specified with `"*"` version requirement (`semver = "*"`).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `conduit` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.5.0
```

**Comment by jtgeibel** [comment]
Seems reasonable to me.  Yanked.
